name: ${name}
description: ${description}
author: ${author}
version: ${version}
url: ${url}
main: dev._2lstudios.chatsentinel.bukkit.ChatSentinel
api: "1.13"
api-version: "1.13"
commands:
  chatsentinel:
    description: "Main command for ChatSentinel plugin"